version: '3'

vars:
  LMB_DOWNLOADER: 1
  LMB_PARSER: 1
  LMB_ML: 1
  LMB_TRANSLATOR: 1
 
tasks:
  deploy:
    desc: Deploy project to AWS
    cmds:
      - task: build
      - task: push
  
  push:
    desc: Push Lambda handler code to AWS
    cmds:
      - echo "TASK - Push Lambda handler code to AWS"
      - ./deploy_lmb.sh {{.LMB_DOWNLOADER}} {{.LMB_PARSER}} {{.LMB_ML}} {{.LMB_TRANSLATOR}}

  build:
    desc: Build Lambda handler code
    cmds:
      - echo "TASK - Build Lambda handler code"
      - ./build_lmb.sh {{.LMB_DOWNLOADER}} {{.LMB_PARSER}} {{.LMB_ML}} {{.LMB_TRANSLATOR}}
